### ISSUE TITLE
Logging integration into GitHub Scratcher

### ISSUE THREAD

**Issue by IamMQaisar** [creativecommons/quantifying#109]
## Description

The latest GitHub Scratcher lacks logging integration, unlike other Scratchers in our suite. This absence of logging functionality creates inconsistency in our codebase.

## Screenshots

![image](https://github.com/creativecommons/quantifying/assets/130001453/ea7f5b72-ce4e-4ee2-a754-c99bb5f223bc)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by ImaJin14** [comment]
hi @IamMQaisar the issue hasn't been approved, hence it can't be worked on as per the How to contribute rules.

**Comment by IamMQaisar** [comment]
But the PR was reviewed by @TimidRobot , don't know why the issue hasn't labeled as open yet.
