### ISSUE TITLE
[Bug] link formatting in Readme.md

### ISSUE THREAD

**Issue by satyampsoni** [creativecommons/quantifying#55]
## Description

In the [README.md](https://github.com/creativecommons/quantifying#readme) every link that is present in the repository is  `inline-block` except sources.md. Put sources.md in inline-block like `history.md` as shown in the screenshot.

https://github.com/creativecommons/quantifying/blob/8c444b52f560b034ecf464dafdea34ca520afc91/README.md?plain=1#L84

## Screenshots
![image](https://user-images.githubusercontent.com/94950988/229880962-6a48c97c-25b7-48ff-b734-f012f88ee945.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by chetan0402** [comment]
there you go

**Comment by satyampsoni** [comment]
This should be closed now
