### ISSUE TITLE
[Feature] Requirements.txt to install preqs dependencies for python.

### ISSUE THREAD

**Issue by cyai** [creativecommons/quantifying#63]
## Problem

The user has to manually install the dependencies before running `tools.sh` file.

## Description

Having a requirements.txt file with the minimum dependencies like black, flake8 etc which the user might be able to install at once after creating the virtual environment for the project.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by cyai** [comment]
Submitted a PR for the same issue here #64

**Comment by Paulooh007** [comment]
The repo uses `pipenv` to manage dependencies, which  eliminates the need for a `requirements.txt` file. The requirements  are in [`Pipfile.lock`](https://github.com/creativecommons/quantifying/blob/main/Pipfile.lock)

**Comment by cyai** [comment]
Makes sense, so we don't need to use pip? if not then I'll close the issue!

**Comment by Paulooh007** [comment]
You'll need to first install `pipenv` (`pip install pipenv `should do), then run `pipenv sync --dev`.  Like in the readme.
