### ISSUE TITLE
Utilize organization default community health files

### ISSUE THREAD

**Issue by nox1134** [creativecommons/quantifying#87]
## Description
Remove duplicate files from the repository to ensure alignment with organizational defaults as outlined in GitHub Repo Guidelines.

Related to:
- creativecommons/.github#38

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by IamMQaisar** [comment]
I've also opened the related issue for the unorganized codebase, Review #86, as it mentioned both comments and the codebase issue.

**Comment by IamMQaisar** [comment]
Checked the relavent pull request for this issue now, that is not what I intended to mention is this works fine. Thanks
